package app

import (
	"archive/tar"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type PluginBundleInstallOptions struct {
	Archive string
	Dest    string
	Force   bool
}

type PluginBundleInstallResult struct {
	Lines []string
}

func (PluginService) BundleInstall(opts PluginBundleInstallOptions) (PluginBundleInstallResult, error) {
	archivePath := strings.TrimSpace(opts.Archive)
	if archivePath == "" {
		return PluginBundleInstallResult{}, fmt.Errorf("bundle install requires a local .tar.gz bundle path")
	}
	lowerArchivePath := strings.ToLower(archivePath)
	if strings.HasPrefix(lowerArchivePath, "http://") || strings.HasPrefix(lowerArchivePath, "https://") {
		return PluginBundleInstallResult{}, fmt.Errorf("bundle install supports local .tar.gz bundles only; remote URLs are out of scope")
	}
	if !strings.HasSuffix(lowerArchivePath, ".tar.gz") {
		return PluginBundleInstallResult{}, fmt.Errorf("bundle install requires a local .tar.gz bundle path")
	}
	dest := strings.TrimSpace(opts.Dest)
	if dest == "" {
		return PluginBundleInstallResult{}, fmt.Errorf("bundle install requires --dest")
	}

	metadata, err := inspectBundleArchive(archivePath)
	if err != nil {
		return PluginBundleInstallResult{}, err
	}
	if err := validateBundleMetadata(metadata); err != nil {
		return PluginBundleInstallResult{}, err
	}

	installedPath, err := installBundleArchive(archivePath, dest, opts.Force)
	if err != nil {
		return PluginBundleInstallResult{}, err
	}

	lines := []string{
		fmt.Sprintf("Bundle: plugin=%s platform=%s runtime=%s manager=%s", metadata.PluginName, metadata.Platform, metadata.Runtime, displayBundleManager(metadata.Manager)),
		"Bundle source: " + archivePath,
		"Installed path: " + installedPath,
		"Next:",
	}
	for _, step := range resolvedBundleNext(metadata, installedPath) {
		lines = append(lines, "  "+step)
	}
	return PluginBundleInstallResult{Lines: lines}, nil
}

func inspectBundleArchive(archivePath string) (exportMetadata, error) {
	tr, closer, err := openBundleArchive(archivePath)
	if err != nil {
		return exportMetadata{}, err
	}
	defer closer()

	var metadata exportMetadata
	foundMetadata := false
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return exportMetadata{}, err
		}
		name, err := validateBundleHeader(hdr)
		if err != nil {
			return exportMetadata{}, err
		}
		if hdr.Typeflag == tar.TypeDir {
			continue
		}
		body, err := io.ReadAll(tr)
		if err != nil {
			return exportMetadata{}, err
		}
		if name != ".plugin-kit-ai-export.json" {
			continue
		}
		if err := json.Unmarshal(body, &metadata); err != nil {
			return exportMetadata{}, fmt.Errorf("bundle install requires valid .plugin-kit-ai-export.json: %w", err)
		}
		foundMetadata = true
	}
	if !foundMetadata {
		return exportMetadata{}, fmt.Errorf("bundle install requires .plugin-kit-ai-export.json in archive root")
	}
	return metadata, nil
}

func validateBundleMetadata(metadata exportMetadata) error {
	if strings.TrimSpace(metadata.BundleFormat) != "tar.gz" {
		return fmt.Errorf("bundle install supports only plugin-kit-ai export tar.gz bundles")
	}
	if strings.TrimSpace(metadata.GeneratedBy) != "plugin-kit-ai export" {
		return fmt.Errorf("bundle install requires archives generated by plugin-kit-ai export")
	}
	if strings.TrimSpace(metadata.PluginName) == "" {
		return fmt.Errorf("bundle install requires metadata.plugin_name")
	}
	switch metadata.Platform {
	case "codex-runtime", "claude":
	default:
		return fmt.Errorf("bundle install supports only codex-runtime or claude bundles; found %q", metadata.Platform)
	}
	switch metadata.Runtime {
	case "python", "node":
	default:
		return fmt.Errorf("bundle install supports only exported python/node bundles; found runtime %q", metadata.Runtime)
	}
	return nil
}

func installBundleArchive(archivePath, dest string, force bool) (string, error) {
	dest = filepath.Clean(dest)
	parent := filepath.Dir(dest)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return "", err
	}

	tmp, err := os.MkdirTemp(parent, ".plugin-kit-ai-bundle-*")
	if err != nil {
		return "", err
	}
	success := false
	defer func() {
		if !success {
			_ = os.RemoveAll(tmp)
		}
	}()

	tr, closer, err := openBundleArchive(archivePath)
	if err != nil {
		return "", err
	}
	defer closer()

	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", err
		}
		name, err := validateBundleHeader(hdr)
		if err != nil {
			return "", err
		}
		target := filepath.Join(tmp, filepath.FromSlash(name))
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, os.FileMode(hdr.Mode)); err != nil {
				return "", err
			}
		case tar.TypeReg, tar.TypeRegA:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return "", err
			}
			body, err := io.ReadAll(tr)
			if err != nil {
				return "", err
			}
			if err := os.WriteFile(target, body, os.FileMode(hdr.Mode)); err != nil {
				return "", err
			}
		default:
			return "", fmt.Errorf("bundle install refuses unsupported archive entry %s", name)
		}
	}

	exists, err := pathExists(dest)
	if err != nil {
		return "", err
	}
	if exists {
		empty, err := pathEmpty(dest)
		if err != nil {
			return "", err
		}
		if !force && !empty {
			return "", fmt.Errorf("bundle install destination %s already exists and is not empty; use --force to overwrite", dest)
		}
		if err := os.RemoveAll(dest); err != nil {
			return "", err
		}
	}

	if err := os.Rename(tmp, dest); err != nil {
		return "", err
	}
	success = true
	return dest, nil
}

func openBundleArchive(path string) (*tar.Reader, func() error, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, nil, err
	}
	gz, err := gzip.NewReader(f)
	if err != nil {
		_ = f.Close()
		return nil, nil, err
	}
	closeFn := func() error {
		err1 := gz.Close()
		err2 := f.Close()
		if err1 != nil {
			return err1
		}
		return err2
	}
	return tar.NewReader(gz), closeFn, nil
}

func validateBundleHeader(hdr *tar.Header) (string, error) {
	name := normalizeExportPath(hdr.Name)
	if name == "" {
		return "", fmt.Errorf("bundle install refuses invalid archive path %q", hdr.Name)
	}
	if strings.HasPrefix(name, "../") || strings.Contains(name, "/../") {
		return "", fmt.Errorf("bundle install refuses path traversal entry %s", hdr.Name)
	}
	if filepath.IsAbs(hdr.Name) {
		return "", fmt.Errorf("bundle install refuses absolute archive path %s", hdr.Name)
	}
	switch hdr.Typeflag {
	case tar.TypeReg, tar.TypeRegA, tar.TypeDir:
		return name, nil
	case tar.TypeSymlink, tar.TypeLink:
		return "", fmt.Errorf("bundle install refuses symlink entry %s", hdr.Name)
	default:
		return "", fmt.Errorf("bundle install refuses unsupported archive entry %s", hdr.Name)
	}
}

func pathExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}

func pathEmpty(path string) (bool, error) {
	info, err := os.Stat(path)
	if err != nil {
		return false, err
	}
	if !info.IsDir() {
		return false, nil
	}
	entries, err := os.ReadDir(path)
	if err != nil {
		return false, err
	}
	return len(entries) == 0, nil
}

func resolvedBundleNext(metadata exportMetadata, dest string) []string {
	if len(metadata.Next) == 0 {
		return canonicalBundleNext(metadata.Platform, dest)
	}
	out := make([]string, 0, len(metadata.Next))
	for _, step := range metadata.Next {
		step = strings.TrimSpace(step)
		if step == "" {
			continue
		}
		out = append(out, strings.Replace(step, " .", " "+dest, 1))
	}
	if len(out) == 0 {
		return canonicalBundleNext(metadata.Platform, dest)
	}
	return out
}

func canonicalBundleNext(platform, dest string) []string {
	return []string{
		"plugin-kit-ai doctor " + dest,
		"plugin-kit-ai bootstrap " + dest,
		fmt.Sprintf("plugin-kit-ai validate %s --platform %s --strict", dest, platform),
	}
}

func displayBundleManager(manager string) string {
	manager = strings.TrimSpace(manager)
	if manager == "" {
		return "none"
	}
	return manager
}
