package app

import (
	"archive/tar"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func validateBundleMetadata(metadata exportMetadata) error {
	if err := validateBundleMetadataEnvelope(metadata); err != nil {
		return err
	}
	return validateBundleMetadataRuntime(metadata)
}

func installBundleArchive(archivePath, dest string, force bool) (string, error) {
	dest = filepath.Clean(dest)
	tmp, cleanup, err := prepareBundleInstallWorkspace(dest)
	if err != nil {
		return "", err
	}
	success := false
	defer func() {
		if !success {
			cleanup()
		}
	}()

	if err := extractBundleArchiveToDir(archivePath, tmp); err != nil {
		return "", err
	}
	if err := replaceInstalledBundle(tmp, dest, force); err != nil {
		return "", err
	}
	success = true
	return dest, nil
}

func extractBundleArchive(tr *tar.Reader, dest string) error {
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		if err := extractBundleArchiveEntry(tr, dest, hdr); err != nil {
			return err
		}
	}
}

func replaceInstalledBundle(tmp, dest string, force bool) error {
	exists, err := pathExists(dest)
	if err != nil {
		return err
	}
	if exists {
		empty, err := pathEmpty(dest)
		if err != nil {
			return err
		}
		if !force && !empty {
			return fmt.Errorf("bundle install destination %s already exists and is not empty; use --force to overwrite", dest)
		}
		if err := os.RemoveAll(dest); err != nil {
			return err
		}
	}
	return os.Rename(tmp, dest)
}

func validateBundleMetadataEnvelope(metadata exportMetadata) error {
	if strings.TrimSpace(metadata.BundleFormat) != "tar.gz" {
		return fmt.Errorf("bundle install supports only plugin-kit-ai export tar.gz bundles")
	}
	if strings.TrimSpace(metadata.GeneratedBy) != "plugin-kit-ai export" {
		return fmt.Errorf("bundle install requires archives generated by plugin-kit-ai export")
	}
	if strings.TrimSpace(metadata.PluginName) == "" {
		return fmt.Errorf("bundle install requires metadata.plugin_name")
	}
	return nil
}

func validateBundleMetadataRuntime(metadata exportMetadata) error {
	switch metadata.Platform {
	case "codex-runtime", "claude":
	default:
		return fmt.Errorf("bundle install supports only codex-runtime or claude bundles; found %q", metadata.Platform)
	}
	switch metadata.Runtime {
	case "python", "node":
	default:
		return fmt.Errorf("bundle install supports only exported python/node bundles; found runtime %q", metadata.Runtime)
	}
	return nil
}
