package app

import (
	"archive/tar"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func validateBundleMetadata(metadata exportMetadata) error {
	if strings.TrimSpace(metadata.BundleFormat) != "tar.gz" {
		return fmt.Errorf("bundle install supports only plugin-kit-ai export tar.gz bundles")
	}
	if strings.TrimSpace(metadata.GeneratedBy) != "plugin-kit-ai export" {
		return fmt.Errorf("bundle install requires archives generated by plugin-kit-ai export")
	}
	if strings.TrimSpace(metadata.PluginName) == "" {
		return fmt.Errorf("bundle install requires metadata.plugin_name")
	}
	switch metadata.Platform {
	case "codex-runtime", "claude":
	default:
		return fmt.Errorf("bundle install supports only codex-runtime or claude bundles; found %q", metadata.Platform)
	}
	switch metadata.Runtime {
	case "python", "node":
	default:
		return fmt.Errorf("bundle install supports only exported python/node bundles; found runtime %q", metadata.Runtime)
	}
	return nil
}

func installBundleArchive(archivePath, dest string, force bool) (string, error) {
	dest = filepath.Clean(dest)
	parent := filepath.Dir(dest)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return "", err
	}

	tmp, err := os.MkdirTemp(parent, ".plugin-kit-ai-bundle-*")
	if err != nil {
		return "", err
	}
	success := false
	defer func() {
		if !success {
			_ = os.RemoveAll(tmp)
		}
	}()

	tr, closer, err := openBundleArchive(archivePath)
	if err != nil {
		return "", err
	}
	defer closer()

	if err := extractBundleArchive(tr, tmp); err != nil {
		return "", err
	}
	if err := replaceInstalledBundle(tmp, dest, force); err != nil {
		return "", err
	}
	success = true
	return dest, nil
}

func extractBundleArchive(tr *tar.Reader, dest string) error {
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		name, err := validateBundleHeader(hdr)
		if err != nil {
			return err
		}
		target := filepath.Join(dest, filepath.FromSlash(name))
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, os.FileMode(hdr.Mode)); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			body, err := io.ReadAll(tr)
			if err != nil {
				return err
			}
			if err := os.WriteFile(target, body, os.FileMode(hdr.Mode)); err != nil {
				return err
			}
		default:
			return fmt.Errorf("bundle install refuses unsupported archive entry %s", name)
		}
	}
}

func replaceInstalledBundle(tmp, dest string, force bool) error {
	exists, err := pathExists(dest)
	if err != nil {
		return err
	}
	if exists {
		empty, err := pathEmpty(dest)
		if err != nil {
			return err
		}
		if !force && !empty {
			return fmt.Errorf("bundle install destination %s already exists and is not empty; use --force to overwrite", dest)
		}
		if err := os.RemoveAll(dest); err != nil {
			return err
		}
	}
	return os.Rename(tmp, dest)
}
