package platformmeta

func geminiProfile() PlatformProfile {
	return PlatformProfile{
		ID: "gemini",
		Contract: TargetContractMeta{
			PlatformFamily:         FamilyExtensionPackage,
			TargetClass:            "mcp_extension",
			TargetNoun:             "extension",
			ProductionClass:        "production-ready extension packaging lane",
			RuntimeContract:        "production-ready extension packaging plus optional production-ready 9-hook Go runtime",
			InstallModel:           "copy install",
			DevModel:               "link",
			ActivationModel:        "restart required",
			NativeRoot:             "~/.gemini/extensions/<name>",
			ImportSupport:          true,
			GenerateSupport:        true,
			ValidateSupport:        true,
			PortableComponentKinds: []string{"skills", "mcp_servers"},
			TargetComponentKinds:   []string{"package_metadata", "hooks", "commands", "policies", "themes", "settings", "contexts", "manifest_extra"},
			Summary:                "Gemini compiles as an official-style extension package with MCP, a primary root context, target-native extension assets, and an optional production-ready Go hook runtime lane.",
		},
		SDK: SDKMeta{
			PublicPackage:   "gemini",
			InternalPackage: "gemini",
			InternalImport:  "github.com/777genius/plugin-kit-ai/sdk/internal/platforms/gemini",
			Status:          StatusRuntimeSupported,
			TransportModes:  []TransportMode{TransportProcess},
			LiveTestProfile: "gemini_extension",
		},
		Launcher: LauncherMeta{Requirement: LauncherOptional},
		NativeDocs: []NativeDocSpec{
			{Kind: "package_metadata", Path: "src/targets/gemini/package.yaml", Format: NativeDocYAML, Role: NativeDocRoleStructured},
			{Kind: "manifest_extra", Path: "src/targets/gemini/manifest.extra.json", Format: NativeDocJSON, Role: NativeDocRoleExtra, ManagedKeys: []string{"name", "version", "description", "mcpServers", "contextFileName", "excludeTools", "migratedTo", "settings", "themes", "plan.directory"}},
		},
		SurfaceTiers: []SurfaceSupport{
			{Kind: "commands", Tier: SurfaceTierStable},
			{Kind: "hooks", Tier: SurfaceTierStable},
			{Kind: "policies", Tier: SurfaceTierStable},
			{Kind: "settings", Tier: SurfaceTierStable},
			{Kind: "themes", Tier: SurfaceTierStable},
			{Kind: "contexts", Tier: SurfaceTierStable},
			{Kind: "manifest_extra", Tier: SurfaceTierStable},
			{Kind: "agents", Tier: SurfaceTierPreview},
		},
		ManagedArtifacts: []ManagedArtifactSpec{
			{Kind: ManagedArtifactStatic, Path: "gemini-extension.json"},
			{Kind: ManagedArtifactPortableSkills, SourceRoot: "src/skills", OutputRoot: "skills"},
			{Kind: ManagedArtifactMirror, ComponentKind: "hooks", SourceRoot: "src/targets/gemini/hooks", OutputRoot: "hooks"},
			{Kind: ManagedArtifactMirror, ComponentKind: "commands", SourceRoot: "src/targets/gemini/commands", OutputRoot: "commands"},
			{Kind: ManagedArtifactMirror, ComponentKind: "policies", SourceRoot: "src/targets/gemini/policies", OutputRoot: "policies"},
			{Kind: ManagedArtifactMirror, ComponentKind: "contexts", SourceRoot: "src/targets/gemini/contexts", OutputRoot: "contexts"},
			{Kind: ManagedArtifactSelectedContext, ComponentKind: "contexts", OutputRoot: "", ContextMode: ContextStrategyGeminiPrimaryRoot},
		},
		Scaffold: ScaffoldMeta{
			RequiredFiles: []string{
				"src/plugin.yaml",
				"src/targets/gemini/package.yaml",
				"src/targets/gemini/contexts/GEMINI.md",
				"src/README.md",
				"CLAUDE.md",
				"AGENTS.md",
			},
			OptionalFiles: []string{
				"Makefile",
				".goreleaser.yml",
				"src/skills/{{.ProjectName}}/SKILL.md",
			},
			TemplateFiles: []TemplateFile{
				{Path: "src/plugin.yaml", Template: "plugin.yaml.tmpl"},
				{Path: "src/targets/gemini/package.yaml", Template: "targets.gemini.package.yaml.tmpl"},
				{Path: "src/targets/gemini/contexts/GEMINI.md", Template: "gemini.GEMINI.md.tmpl"},
				{Path: "src/README.md", Template: "gemini.README.md.tmpl"},
				{Path: "CLAUDE.md", Template: "ROOT.CLAUDE.md.tmpl"},
				{Path: "AGENTS.md", Template: "ROOT.AGENTS.md.tmpl"},
				{Path: "Makefile", Template: "Makefile.tmpl", Extra: true},
				{Path: ".goreleaser.yml", Template: "goreleaser.yml.tmpl", Extra: true},
				{Path: "src/skills/{{.ProjectName}}/SKILL.md", Template: "SKILL.md.tmpl", Extra: true},
			},
		},
		Validate: ValidateMeta{
			RequiredFiles: []string{
				"README.md",
				"gemini-extension.json",
			},
		},
	}
}

func cursorProfile() PlatformProfile {
	return PlatformProfile{
		ID: "cursor",
		Contract: TargetContractMeta{
			PlatformFamily:         FamilyIDEPlugin,
			TargetClass:            "plugin_package",
			TargetNoun:             "plugin",
			ProductionClass:        "packaging-only target",
			RuntimeContract:        "Cursor marketplace plugin bundle with portable skills and optional portable MCP",
			InstallModel:           "marketplace or /add-plugin install",
			DevModel:               "package authoring workspace",
			ActivationModel:        "plugin reload or restart",
			NativeRoot:             ".cursor-plugin/plugin.json",
			ImportSupport:          true,
			GenerateSupport:        true,
			ValidateSupport:        true,
			PortableComponentKinds: []string{"skills", "mcp_servers"},
			TargetComponentKinds:   []string{},
			Summary:                "Cursor plugin packages compile portable skills and optional shared MCP into the current observed .cursor-plugin bundle shape without inventing unsupported target-native authoring surfaces.",
		},
		SDK: SDKMeta{
			PublicPackage:   "cursor",
			InternalPackage: "cursor",
			InternalImport:  "github.com/777genius/plugin-kit-ai/sdk/internal/platforms/cursor",
			Status:          StatusScaffoldOnly,
			TransportModes:  []TransportMode{TransportProcess},
			LiveTestProfile: "cursor_plugin",
		},
		Launcher: LauncherMeta{Requirement: LauncherIgnored},
		SurfaceTiers: []SurfaceSupport{
			{Kind: "rules", Tier: SurfaceTierUnsupported},
			{Kind: "agents_markdown", Tier: SurfaceTierUnsupported},
			{Kind: "hooks", Tier: SurfaceTierUnsupported},
			{Kind: "commands", Tier: SurfaceTierUnsupported},
			{Kind: "subagents", Tier: SurfaceTierUnsupported},
		},
		ManagedArtifacts: []ManagedArtifactSpec{
			{Kind: ManagedArtifactStatic, Path: ".cursor-plugin/plugin.json"},
			{Kind: ManagedArtifactPortableSkills, SourceRoot: "src/skills", OutputRoot: "skills"},
			{Kind: ManagedArtifactPortableMCP, Path: ".mcp.json"},
		},
		Scaffold: ScaffoldMeta{
			RequiredFiles: []string{
				"src/plugin.yaml",
				"src/README.md",
				"CLAUDE.md",
				"AGENTS.md",
			},
			OptionalFiles: []string{
				"src/mcp/servers.yaml",
				"src/skills/{{.ProjectName}}/SKILL.md",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
			TemplateFiles: []TemplateFile{
				{Path: "src/plugin.yaml", Template: "plugin.yaml.tmpl"},
				{Path: "src/README.md", Template: "cursor.README.md.tmpl"},
				{Path: "src/mcp/servers.yaml", Template: "mcp.servers.yaml.tmpl", Extra: true},
				{Path: "src/skills/{{.ProjectName}}/SKILL.md", Template: "SKILL.md.tmpl", Extra: true},
				{Path: "CLAUDE.md", Template: "ROOT.CLAUDE.md.tmpl"},
				{Path: "AGENTS.md", Template: "ROOT.AGENTS.md.tmpl"},
			},
		},
		Validate: ValidateMeta{
			RequiredFiles: []string{
				"README.md",
				".cursor-plugin/plugin.json",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
		},
	}
}

func cursorWorkspaceProfile() PlatformProfile {
	return PlatformProfile{
		ID: "cursor-workspace",
		Contract: TargetContractMeta{
			PlatformFamily:         FamilyCodePlugin,
			TargetClass:            "workspace_config_lane",
			TargetNoun:             "workspace",
			ProductionClass:        "packaging-only target",
			RuntimeContract:        "workspace-config lane with first-class MCP config and project rules",
			InstallModel:           "workspace config files",
			DevModel:               "config authoring workspace",
			ActivationModel:        "config reload or restart",
			NativeRoot:             ".cursor/mcp.json",
			ImportSupport:          true,
			GenerateSupport:        true,
			ValidateSupport:        true,
			PortableComponentKinds: []string{"mcp_servers"},
			TargetComponentKinds:   []string{"rules", "agents_markdown"},
			Summary:                "Cursor workspace compiles as a repo-local config lane with generated .cursor MCP config, project rules, and authored Cursor AGENTS content merged into the generated root AGENTS.md boundary file.",
		},
		SDK: SDKMeta{
			PublicPackage:   "cursor",
			InternalPackage: "cursor",
			InternalImport:  "github.com/777genius/plugin-kit-ai/sdk/internal/platforms/cursor",
			Status:          StatusScaffoldOnly,
			TransportModes:  []TransportMode{TransportProcess},
			LiveTestProfile: "cursor_workspace",
		},
		Launcher: LauncherMeta{Requirement: LauncherIgnored},
		NativeDocs: []NativeDocSpec{
			{Kind: "agents_markdown", Path: "src/targets/cursor-workspace/AGENTS.md", Format: NativeDocMarkdown, Role: NativeDocRoleStructured},
		},
		SurfaceTiers: []SurfaceSupport{
			{Kind: "mcp", Tier: SurfaceTierStable},
			{Kind: "rules", Tier: SurfaceTierStable},
			{Kind: "agents_markdown", Tier: SurfaceTierStable},
		},
		ManagedArtifacts: []ManagedArtifactSpec{
			{Kind: ManagedArtifactPortableMCP, Path: ".cursor/mcp.json"},
			{Kind: ManagedArtifactMirror, ComponentKind: "rules", SourceRoot: "src/targets/cursor-workspace/rules", OutputRoot: ".cursor/rules"},
		},
		Scaffold: ScaffoldMeta{
			RequiredFiles: []string{
				"src/plugin.yaml",
				"src/README.md",
				"src/targets/cursor-workspace/rules/project.mdc",
				"CLAUDE.md",
				"AGENTS.md",
			},
			OptionalFiles: []string{
				"src/targets/cursor-workspace/AGENTS.md",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
			TemplateFiles: []TemplateFile{
				{Path: "src/plugin.yaml", Template: "plugin.yaml.tmpl"},
				{Path: "src/README.md", Template: "cursor-workspace.README.md.tmpl"},
				{Path: "src/targets/cursor-workspace/rules/project.mdc", Template: "cursor.rule.mdc.tmpl"},
				{Path: "src/targets/cursor-workspace/AGENTS.md", Template: "cursor.AGENTS.md.tmpl", Extra: true},
				{Path: "CLAUDE.md", Template: "ROOT.CLAUDE.md.tmpl"},
				{Path: "AGENTS.md", Template: "ROOT.AGENTS.md.tmpl"},
			},
		},
		Validate: ValidateMeta{
			RequiredFiles: []string{
				"README.md",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
		},
	}
}

func opencodeProfile() PlatformProfile {
	return PlatformProfile{
		ID: "opencode",
		Contract: TargetContractMeta{
			PlatformFamily:         FamilyCodePlugin,
			TargetClass:            "workspace_config_lane",
			TargetNoun:             "workspace",
			ProductionClass:        "packaging-only target",
			RuntimeContract:        "workspace-config lane with first-class npm plugin refs including tuple-form options, MCP, skills, commands, agents, default_agent, instructions, permission, themes, beta standalone tools with dedicated live evidence, stable official-style local JS/TS plugins plus shared dependency metadata, JSON/JSONC native import, explicit user-scope import, and sanctioned config.extra passthrough for broader product config",
			InstallModel:           "workspace config file",
			DevModel:               "config authoring workspace",
			ActivationModel:        "config reload or restart",
			NativeRoot:             "opencode.json",
			ImportSupport:          true,
			GenerateSupport:        true,
			ValidateSupport:        true,
			PortableComponentKinds: []string{"skills", "mcp_servers"},
			TargetComponentKinds:   []string{"package_metadata", "config_extra", "default_agent", "instructions_config", "permission_config", "commands", "agents", "themes", "tools", "local_plugin_code", "local_plugin_dependencies"},
			Summary:                "OpenCode compiles as a workspace-config lane with canonical src-authored inputs for npm plugin refs including tuple-form options, shared MCP, skills, commands, agents, default_agent, instructions, permission, themes, beta standalone tools with their own live-evidence path, stable official-style local JS/TS plugins plus shared package metadata for tools and plugins, JSON/JSONC native import plus explicit user-scope import, and sanctioned config.extra passthrough for broader product config.",
		},
		SDK: SDKMeta{
			PublicPackage:   "opencode",
			InternalPackage: "opencode",
			InternalImport:  "github.com/777genius/plugin-kit-ai/sdk/internal/platforms/opencode",
			Status:          StatusScaffoldOnly,
			TransportModes:  []TransportMode{TransportProcess},
			LiveTestProfile: "opencode_workspace",
		},
		Launcher: LauncherMeta{Requirement: LauncherIgnored},
		NativeDocs: []NativeDocSpec{
			{Kind: "package_metadata", Path: "src/targets/opencode/package.yaml", Format: NativeDocYAML, Role: NativeDocRoleStructured},
			{Kind: "config_extra", Path: "src/targets/opencode/config.extra.json", Format: NativeDocJSON, Role: NativeDocRoleExtra, ManagedKeys: []string{"$schema", "plugin", "mcp", "default_agent", "instructions", "permission", "mode"}},
			{Kind: "default_agent", Path: "src/targets/opencode/default_agent.txt", Format: NativeDocMarkdown, Role: NativeDocRoleStructured},
			{Kind: "instructions_config", Path: "src/targets/opencode/instructions.yaml", Format: NativeDocYAML, Role: NativeDocRoleStructured},
			{Kind: "permission_config", Path: "src/targets/opencode/permission.json", Format: NativeDocJSON, Role: NativeDocRoleStructured},
			{Kind: "local_plugin_dependencies", Path: "src/targets/opencode/package.json", Format: NativeDocJSON, Role: NativeDocRoleStructured},
		},
		SurfaceTiers: []SurfaceSupport{
			{Kind: "plugins", Tier: SurfaceTierStable},
			{Kind: "mcp", Tier: SurfaceTierStable},
			{Kind: "skills", Tier: SurfaceTierStable},
			{Kind: "commands", Tier: SurfaceTierStable},
			{Kind: "agents", Tier: SurfaceTierStable},
			{Kind: "themes", Tier: SurfaceTierStable},
			{Kind: "tools", Tier: SurfaceTierBeta},
			{Kind: "config_extra", Tier: SurfaceTierStable},
			{Kind: "agent_config", Tier: SurfaceTierStable},
			{Kind: "default_agent", Tier: SurfaceTierStable},
			{Kind: "permission_config", Tier: SurfaceTierStable},
			{Kind: "instructions_config", Tier: SurfaceTierStable},
			{Kind: "modes", Tier: SurfaceTierUnsupported},
			{Kind: "local_plugin_code", Tier: SurfaceTierStable},
			{Kind: "custom_tools", Tier: SurfaceTierBeta},
			{Kind: "local_plugin_dependencies", Tier: SurfaceTierStable},
		},
		ManagedArtifacts: []ManagedArtifactSpec{
			{Kind: ManagedArtifactStatic, Path: "opencode.json"},
			{Kind: ManagedArtifactStatic, Path: ".opencode/package.json"},
			{Kind: ManagedArtifactPortableSkills, OutputRoot: ".opencode/skills"},
			{Kind: ManagedArtifactMirror, ComponentKind: "commands", SourceRoot: "src/targets/opencode/commands", OutputRoot: ".opencode/commands"},
			{Kind: ManagedArtifactMirror, ComponentKind: "agents", SourceRoot: "src/targets/opencode/agents", OutputRoot: ".opencode/agents"},
			{Kind: ManagedArtifactMirror, ComponentKind: "themes", SourceRoot: "src/targets/opencode/themes", OutputRoot: ".opencode/themes"},
			{Kind: ManagedArtifactMirror, ComponentKind: "tools", SourceRoot: "src/targets/opencode/tools", OutputRoot: ".opencode/tools"},
			{Kind: ManagedArtifactMirror, ComponentKind: "local_plugin_code", SourceRoot: "src/targets/opencode/plugins", OutputRoot: ".opencode/plugins"},
		},
		Scaffold: ScaffoldMeta{
			RequiredFiles: []string{
				"src/plugin.yaml",
				"src/targets/opencode/package.yaml",
				"src/README.md",
				"CLAUDE.md",
				"AGENTS.md",
			},
			OptionalFiles: []string{
				"src/skills/{{.ProjectName}}/SKILL.md",
				"src/targets/opencode/config.extra.json",
				"src/targets/opencode/default_agent.txt",
				"src/targets/opencode/instructions.yaml",
				"src/targets/opencode/permission.json",
				"src/targets/opencode/commands/{{.ProjectName}}.md",
				"src/targets/opencode/agents/{{.ProjectName}}.md",
				"src/targets/opencode/themes/{{.ProjectName}}.json",
				"src/targets/opencode/tools/{{.ProjectName}}.ts",
				"src/targets/opencode/plugins/example.js",
				"src/targets/opencode/package.json",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
			TemplateFiles: []TemplateFile{
				{Path: "src/plugin.yaml", Template: "plugin.yaml.tmpl"},
				{Path: "src/targets/opencode/package.yaml", Template: "targets.opencode.package.yaml.tmpl"},
				{Path: "src/README.md", Template: "opencode.README.md.tmpl"},
				{Path: "CLAUDE.md", Template: "ROOT.CLAUDE.md.tmpl"},
				{Path: "AGENTS.md", Template: "ROOT.AGENTS.md.tmpl"},
				{Path: "src/skills/{{.ProjectName}}/SKILL.md", Template: "opencode.SKILL.md.tmpl", Extra: true},
				{Path: "src/targets/opencode/config.extra.json", Template: "opencode.config.extra.json.tmpl", Extra: true},
				{Path: "src/targets/opencode/default_agent.txt", Template: "opencode.default_agent.txt.tmpl", Extra: true},
				{Path: "src/targets/opencode/instructions.yaml", Template: "opencode.instructions.yaml.tmpl", Extra: true},
				{Path: "src/targets/opencode/permission.json", Template: "opencode.permission.json.tmpl", Extra: true},
				{Path: "src/targets/opencode/commands/{{.ProjectName}}.md", Template: "opencode.command.md.tmpl", Extra: true},
				{Path: "src/targets/opencode/agents/{{.ProjectName}}.md", Template: "opencode.agent.md.tmpl", Extra: true},
				{Path: "src/targets/opencode/themes/{{.ProjectName}}.json", Template: "opencode.theme.json.tmpl", Extra: true},
				{Path: "src/targets/opencode/tools/{{.ProjectName}}.ts", Template: "opencode.tool.ts.tmpl", Extra: true},
				{Path: "src/targets/opencode/plugins/example.js", Template: "opencode.plugin.js.tmpl", Extra: true},
				{Path: "src/targets/opencode/package.json", Template: "opencode.package.json.tmpl", Extra: true},
			},
		},
		Validate: ValidateMeta{
			RequiredFiles: []string{
				"README.md",
				"opencode.json",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
		},
	}
}
