package platformmeta

func claudeProfile() PlatformProfile {
	return PlatformProfile{
		ID: "claude",
		Contract: TargetContractMeta{
			PlatformFamily:         FamilyPackagedRuntime,
			TargetClass:            "hook_runtime",
			TargetNoun:             "plugin",
			ProductionClass:        "production-ready package+runtime lane",
			RuntimeContract:        "package-only config lane plus public-stable stable-subset runtime",
			InstallModel:           "marketplace or local plugin install",
			DevModel:               "reload plugins",
			ActivationModel:        "reload or restart",
			NativeRoot:             "~/.claude/plugins/...",
			ImportSupport:          true,
			GenerateSupport:        true,
			ValidateSupport:        true,
			PortableComponentKinds: []string{"skills", "mcp_servers"},
			TargetComponentKinds:   []string{"package_metadata", "hooks", "commands", "agents", "settings", "lsp", "user_config", "manifest_extra"},
			Summary:                "Claude plugin packages compile portable skills and MCP plus target-native commands, agents, settings, LSP, and user config without launcher.yaml, and optionally add launcher-backed hooks runtime surfaces.",
		},
		SDK: SDKMeta{
			PublicPackage:   "claude",
			InternalPackage: "claude",
			InternalImport:  "github.com/777genius/plugin-kit-ai/sdk/internal/platforms/claude",
			Status:          StatusRuntimeSupported,
			TransportModes:  []TransportMode{TransportProcess},
			LiveTestProfile: "claude_cli",
		},
		Launcher: LauncherMeta{Requirement: LauncherOptional},
		NativeDocs: []NativeDocSpec{
			{Kind: "package_metadata", Path: authoredPath("targets/claude/package.yaml"), Format: NativeDocYAML, Role: NativeDocRoleStructured},
			{Kind: "hooks", Path: authoredPath("targets/claude/hooks/hooks.json"), Format: NativeDocJSON, Role: NativeDocRoleStructured},
			{Kind: "settings", Path: authoredPath("targets/claude/settings.json"), Format: NativeDocJSON, Role: NativeDocRoleStructured},
			{Kind: "lsp", Path: authoredPath("targets/claude/lsp.json"), Format: NativeDocJSON, Role: NativeDocRoleStructured},
			{Kind: "user_config", Path: authoredPath("targets/claude/user-config.json"), Format: NativeDocJSON, Role: NativeDocRoleStructured},
			{Kind: "manifest_extra", Path: authoredPath("targets/claude/manifest.extra.json"), Format: NativeDocJSON, Role: NativeDocRoleExtra, ManagedKeys: []string{"name", "version", "description", "skills", "agents", "commands", "hooks", "mcpServers", "lspServers", "settings", "userConfig"}},
		},
		SurfaceTiers: []SurfaceSupport{
			{Kind: "hooks", Tier: SurfaceTierStable},
			{Kind: "commands", Tier: SurfaceTierStable},
			{Kind: "agents", Tier: SurfaceTierBeta},
			{Kind: "contexts", Tier: SurfaceTierUnsupported},
			{Kind: "settings", Tier: SurfaceTierStable},
			{Kind: "lsp", Tier: SurfaceTierBeta},
			{Kind: "user_config", Tier: SurfaceTierBeta},
			{Kind: "manifest_extra", Tier: SurfaceTierStable},
		},
		ManagedArtifacts: []ManagedArtifactSpec{
			{Kind: ManagedArtifactStatic, Path: ".claude-plugin/plugin.json"},
			{Kind: ManagedArtifactStatic, Path: "settings.json"},
			{Kind: ManagedArtifactStatic, Path: ".lsp.json"},
			{Kind: ManagedArtifactPortableSkills, SourceRoot: authoredPath("skills"), OutputRoot: "skills"},
			{Kind: ManagedArtifactMirror, ComponentKind: "hooks", SourceRoot: authoredPath("targets/claude/hooks"), OutputRoot: "hooks"},
			{Kind: ManagedArtifactMirror, ComponentKind: "commands", SourceRoot: authoredPath("targets/claude/commands"), OutputRoot: "commands"},
			{Kind: ManagedArtifactMirror, ComponentKind: "agents", SourceRoot: authoredPath("targets/claude/agents"), OutputRoot: "agents"},
			{Kind: ManagedArtifactPortableMCP, Path: ".mcp.json"},
		},
		Scaffold: ScaffoldMeta{
			RequiredFiles: []string{
				"go.mod",
				authoredPath("README.md"),
				authoredPath("plugin.yaml"),
				authoredPath("launcher.yaml"),
				authoredPath("targets/claude/hooks/hooks.json"),
				"CLAUDE.md",
				"AGENTS.md",
			},
			OptionalFiles: []string{
				"Makefile",
				".goreleaser.yml",
				authoredPath("targets/claude/settings.json"),
				authoredPath("targets/claude/lsp.json"),
				authoredPath("targets/claude/user-config.json"),
				authoredPath("targets/claude/manifest.extra.json"),
				authoredPath("skills/{{.ProjectName}}/SKILL.md"),
			},
			TemplateFiles: []TemplateFile{
				{Path: "go.mod", Template: "go.mod.tmpl"},
				{Path: "cmd/{{.ProjectName}}/main.go", Template: "main.go.tmpl"},
				{Path: authoredPath("plugin.yaml"), Template: "plugin.yaml.tmpl"},
				{Path: authoredPath("launcher.yaml"), Template: "launcher.yaml.tmpl"},
				{Path: authoredPath("targets/claude/hooks/hooks.json"), Template: "targets.claude.hooks.json.tmpl"},
				{Path: authoredPath("targets/claude/settings.json"), Template: "empty.json.tmpl", Extra: true},
				{Path: authoredPath("targets/claude/lsp.json"), Template: "empty.json.tmpl", Extra: true},
				{Path: authoredPath("targets/claude/user-config.json"), Template: "empty.json.tmpl", Extra: true},
				{Path: authoredPath("targets/claude/manifest.extra.json"), Template: "empty.json.tmpl", Extra: true},
				{Path: authoredPath("README.md"), Template: "README.md.tmpl"},
				{Path: "CLAUDE.md", Template: "ROOT.CLAUDE.md.tmpl"},
				{Path: "AGENTS.md", Template: "ROOT.AGENTS.md.tmpl"},
				{Path: "Makefile", Template: "Makefile.tmpl", Extra: true},
				{Path: ".goreleaser.yml", Template: "goreleaser.yml.tmpl", Extra: true},
				{Path: authoredPath("skills/{{.ProjectName}}/SKILL.md"), Template: "SKILL.md.tmpl", Extra: true},
			},
		},
		Validate: ValidateMeta{
			RequiredFiles: []string{
				"README.md",
				".claude-plugin/plugin.json",
			},
			ForbiddenFiles: []string{
				".codex/config.toml",
			},
		},
	}
}
