package platformmeta

func opencodeProfile() PlatformProfile {
	return PlatformProfile{
		ID: "opencode",
		Contract: TargetContractMeta{
			PlatformFamily:         FamilyCodePlugin,
			TargetClass:            "workspace_config_lane",
			TargetNoun:             "workspace",
			ProductionClass:        "packaging-only target",
			RuntimeContract:        "workspace-config lane with first-class npm plugin refs including tuple-form options, MCP, skills, commands, agents, default_agent, instructions, permission, themes, beta standalone tools with dedicated live evidence, stable official-style local JS/TS plugins plus shared dependency metadata, JSON/JSONC native import, explicit user-scope import, and sanctioned config.extra passthrough for broader product config",
			InstallModel:           "workspace config file",
			DevModel:               "config authoring workspace",
			ActivationModel:        "config reload or restart",
			NativeRoot:             "opencode.json",
			ImportSupport:          true,
			GenerateSupport:        true,
			ValidateSupport:        true,
			PortableComponentKinds: []string{"skills", "mcp_servers"},
			TargetComponentKinds:   []string{"package_metadata", "config_extra", "default_agent", "instructions_config", "permission_config", "commands", "agents", "themes", "tools", "local_plugin_code", "local_plugin_dependencies"},
			Summary:                "OpenCode compiles as a workspace-config lane with canonical src-authored inputs for npm plugin refs including tuple-form options, shared MCP, skills, commands, agents, default_agent, instructions, permission, themes, beta standalone tools with their own live-evidence path, stable official-style local JS/TS plugins plus shared package metadata for tools and plugins, JSON/JSONC native import plus explicit user-scope import, and sanctioned config.extra passthrough for broader product config.",
		},
		SDK: SDKMeta{
			PublicPackage:   "opencode",
			InternalPackage: "opencode",
			InternalImport:  "github.com/777genius/plugin-kit-ai/sdk/internal/platforms/opencode",
			Status:          StatusScaffoldOnly,
			TransportModes:  []TransportMode{TransportProcess},
			LiveTestProfile: "opencode_workspace",
		},
		Launcher: LauncherMeta{Requirement: LauncherIgnored},
		NativeDocs: []NativeDocSpec{
			{Kind: "package_metadata", Path: "src/targets/opencode/package.yaml", Format: NativeDocYAML, Role: NativeDocRoleStructured},
			{Kind: "config_extra", Path: "src/targets/opencode/config.extra.json", Format: NativeDocJSON, Role: NativeDocRoleExtra, ManagedKeys: []string{"$schema", "plugin", "mcp", "default_agent", "instructions", "permission", "mode"}},
			{Kind: "default_agent", Path: "src/targets/opencode/default_agent.txt", Format: NativeDocMarkdown, Role: NativeDocRoleStructured},
			{Kind: "instructions_config", Path: "src/targets/opencode/instructions.yaml", Format: NativeDocYAML, Role: NativeDocRoleStructured},
			{Kind: "permission_config", Path: "src/targets/opencode/permission.json", Format: NativeDocJSON, Role: NativeDocRoleStructured},
			{Kind: "local_plugin_dependencies", Path: "src/targets/opencode/package.json", Format: NativeDocJSON, Role: NativeDocRoleStructured},
		},
		SurfaceTiers: []SurfaceSupport{
			{Kind: "plugins", Tier: SurfaceTierStable},
			{Kind: "mcp", Tier: SurfaceTierStable},
			{Kind: "skills", Tier: SurfaceTierStable},
			{Kind: "commands", Tier: SurfaceTierStable},
			{Kind: "agents", Tier: SurfaceTierStable},
			{Kind: "themes", Tier: SurfaceTierStable},
			{Kind: "tools", Tier: SurfaceTierBeta},
			{Kind: "config_extra", Tier: SurfaceTierStable},
			{Kind: "agent_config", Tier: SurfaceTierStable},
			{Kind: "default_agent", Tier: SurfaceTierStable},
			{Kind: "permission_config", Tier: SurfaceTierStable},
			{Kind: "instructions_config", Tier: SurfaceTierStable},
			{Kind: "modes", Tier: SurfaceTierUnsupported},
			{Kind: "local_plugin_code", Tier: SurfaceTierStable},
			{Kind: "custom_tools", Tier: SurfaceTierBeta},
			{Kind: "local_plugin_dependencies", Tier: SurfaceTierStable},
		},
		ManagedArtifacts: []ManagedArtifactSpec{
			{Kind: ManagedArtifactStatic, Path: "opencode.json"},
			{Kind: ManagedArtifactStatic, Path: ".opencode/package.json"},
			{Kind: ManagedArtifactPortableSkills, OutputRoot: ".opencode/skills"},
			{Kind: ManagedArtifactMirror, ComponentKind: "commands", SourceRoot: "src/targets/opencode/commands", OutputRoot: ".opencode/commands"},
			{Kind: ManagedArtifactMirror, ComponentKind: "agents", SourceRoot: "src/targets/opencode/agents", OutputRoot: ".opencode/agents"},
			{Kind: ManagedArtifactMirror, ComponentKind: "themes", SourceRoot: "src/targets/opencode/themes", OutputRoot: ".opencode/themes"},
			{Kind: ManagedArtifactMirror, ComponentKind: "tools", SourceRoot: "src/targets/opencode/tools", OutputRoot: ".opencode/tools"},
			{Kind: ManagedArtifactMirror, ComponentKind: "local_plugin_code", SourceRoot: "src/targets/opencode/plugins", OutputRoot: ".opencode/plugins"},
		},
		Scaffold: ScaffoldMeta{
			RequiredFiles: []string{
				"src/plugin.yaml",
				"src/targets/opencode/package.yaml",
				"src/README.md",
				"CLAUDE.md",
				"AGENTS.md",
			},
			OptionalFiles: []string{
				"src/skills/{{.ProjectName}}/SKILL.md",
				"src/targets/opencode/config.extra.json",
				"src/targets/opencode/default_agent.txt",
				"src/targets/opencode/instructions.yaml",
				"src/targets/opencode/permission.json",
				"src/targets/opencode/commands/{{.ProjectName}}.md",
				"src/targets/opencode/agents/{{.ProjectName}}.md",
				"src/targets/opencode/themes/{{.ProjectName}}.json",
				"src/targets/opencode/tools/{{.ProjectName}}.ts",
				"src/targets/opencode/plugins/example.js",
				"src/targets/opencode/package.json",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
			TemplateFiles: []TemplateFile{
				{Path: "src/plugin.yaml", Template: "plugin.yaml.tmpl"},
				{Path: "src/targets/opencode/package.yaml", Template: "targets.opencode.package.yaml.tmpl"},
				{Path: "src/README.md", Template: "opencode.README.md.tmpl"},
				{Path: "CLAUDE.md", Template: "ROOT.CLAUDE.md.tmpl"},
				{Path: "AGENTS.md", Template: "ROOT.AGENTS.md.tmpl"},
				{Path: "src/skills/{{.ProjectName}}/SKILL.md", Template: "opencode.SKILL.md.tmpl", Extra: true},
				{Path: "src/targets/opencode/config.extra.json", Template: "opencode.config.extra.json.tmpl", Extra: true},
				{Path: "src/targets/opencode/default_agent.txt", Template: "opencode.default_agent.txt.tmpl", Extra: true},
				{Path: "src/targets/opencode/instructions.yaml", Template: "opencode.instructions.yaml.tmpl", Extra: true},
				{Path: "src/targets/opencode/permission.json", Template: "opencode.permission.json.tmpl", Extra: true},
				{Path: "src/targets/opencode/commands/{{.ProjectName}}.md", Template: "opencode.command.md.tmpl", Extra: true},
				{Path: "src/targets/opencode/agents/{{.ProjectName}}.md", Template: "opencode.agent.md.tmpl", Extra: true},
				{Path: "src/targets/opencode/themes/{{.ProjectName}}.json", Template: "opencode.theme.json.tmpl", Extra: true},
				{Path: "src/targets/opencode/tools/{{.ProjectName}}.ts", Template: "opencode.tool.ts.tmpl", Extra: true},
				{Path: "src/targets/opencode/plugins/example.js", Template: "opencode.plugin.js.tmpl", Extra: true},
				{Path: "src/targets/opencode/package.json", Template: "opencode.package.json.tmpl", Extra: true},
			},
		},
		Validate: ValidateMeta{
			RequiredFiles: []string{
				"README.md",
				"opencode.json",
			},
			ForbiddenFiles: []string{
				"launcher.yaml",
			},
		},
	}
}
