// Code generated by the release-bound Directory bootstrap step; DO NOT EDIT.
// The first production signed publication will replace this exact empty tuple.
package main

import "github.com/777genius/plugin-kit-ai/install/integrationctl/agentplugins/adapters/directoryv1"

var generatedProductionDirectoryBootstrap = directoryv1.ReleaseBootstrapEncoding{
	Sequence:       0,
	SnapshotBase64: "",
	EnvelopeBase64: "",
}
