package pluginmanifest

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/777genius/plugin-kit-ai/cli/internal/platformexec"
	"github.com/777genius/plugin-kit-ai/cli/internal/publicationexec"
	"github.com/777genius/plugin-kit-ai/cli/internal/publishschema"
	"github.com/777genius/plugin-kit-ai/cli/internal/scaffold"
)

const (
	managedGuidanceStart      = "<!-- plugin-kit-ai:begin managed-guidance -->"
	managedGuidanceEnd        = "<!-- plugin-kit-ai:end managed-guidance -->"
	managedRootReadmeSentinel = "<!-- plugin-kit-ai:managed-root-readme -->"
	legacyManagedReadmeLine   = "This file is generated by `plugin-kit-ai generate`."
)

func buildRootReadmeArtifact(root string, layout authoredLayout, manifest Manifest) (*Artifact, error) {
	authoredReadme := layout.Path("README.md")
	authoredReadmePath := filepath.Join(root, authoredReadme)
	if _, err := os.Stat(authoredReadmePath); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	managed, err := shouldManageRootReadme(root)
	if err != nil {
		return nil, err
	}
	if !managed {
		return nil, nil
	}
	title := strings.TrimSpace(manifest.Name)
	if title == "" {
		title = "plugin"
	}
	var body strings.Builder
	body.WriteString(managedRootReadmeSentinel)
	body.WriteString("\n")
	body.WriteString("# ")
	body.WriteString(title)
	body.WriteString("\n\n")
	body.WriteString("This file is generated by `plugin-kit-ai generate`.\n")
	body.WriteString("Do not edit it by hand. Edit files under `")
	body.WriteString(layout.Path(""))
	body.WriteString("/`, especially [`")
	body.WriteString(authoredReadme)
	body.WriteString("`](./")
	body.WriteString(authoredReadme)
	body.WriteString(").\n\n")
	body.WriteString("Start here:\n\n")
	body.WriteString("- full plugin guide: [`")
	body.WriteString(authoredReadme)
	body.WriteString("`](./")
	body.WriteString(authoredReadme)
	body.WriteString(")\n")
	body.WriteString("- boundary instructions for humans and agents: [`AGENTS.md`](./AGENTS.md)\n")
	body.WriteString("- generated root output inventory: [`GENERATED.md`](./GENERATED.md)\n\n")
	body.WriteString("This plugin root is the native/generated output surface for the supported targets.\n")
	artifact := Artifact{RelPath: "README.md", Content: []byte(body.String())}
	return &artifact, nil
}

func shouldManageRootReadme(root string) (bool, error) {
	body, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, err
	}
	text := normalizeManagedText(string(body))
	return strings.Contains(text, managedRootReadmeSentinel) || strings.Contains(text, legacyManagedReadmeLine), nil
}

func buildRootClaudeBoundaryArtifact(root string, layout authoredLayout) (*Artifact, error) {
	body, _, err := scaffold.RenderTemplate("ROOT.CLAUDE.md.tmpl", scaffold.Data{
		AuthoredRoot:       layout.Path(""),
		AuthoredReadmePath: layout.Path("README.md"),
	})
	if err != nil {
		return nil, err
	}
	merged, err := mergeManagedGuidanceFile(root, "CLAUDE.md", string(body))
	if err != nil {
		return nil, err
	}
	return &Artifact{RelPath: "CLAUDE.md", Content: []byte(merged)}, nil
}

func buildRootAgentsBoundaryArtifact(root string, layout authoredLayout, graph PackageGraph) (*Artifact, error) {
	body, _, err := scaffold.RenderTemplate("ROOT.AGENTS.md.tmpl", scaffold.Data{
		AuthoredRoot:       layout.Path(""),
		AuthoredReadmePath: layout.Path("README.md"),
	})
	if err != nil {
		return nil, err
	}
	withCursor, err := injectCursorAgentsSection(root, string(body), graph.Targets["cursor-workspace"])
	if err != nil {
		return nil, err
	}
	merged, err := mergeManagedGuidanceFile(root, "AGENTS.md", withCursor)
	if err != nil {
		return nil, err
	}
	return &Artifact{RelPath: "AGENTS.md", Content: []byte(merged)}, nil
}

func injectCursorAgentsSection(root, body string, state TargetState) (string, error) {
	rel := strings.TrimSpace(state.DocPath("agents_markdown"))
	if rel == "" {
		return body, nil
	}
	authored, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		return "", err
	}
	content := strings.TrimSpace(string(authored))
	if content == "" {
		return body, nil
	}
	cursorSection := "\n\n" + platformexec.CursorAgentsSectionStart() + "\n" + content + "\n" + platformexec.CursorAgentsSectionEnd() + "\n"
	idx := strings.Index(body, managedGuidanceEnd)
	if idx < 0 {
		return body + cursorSection, nil
	}
	return body[:idx] + cursorSection + body[idx:], nil
}

func mergeManagedGuidanceFile(root, relPath, generated string) (string, error) {
	generated = strings.TrimRight(normalizeManagedText(generated), "\n") + "\n"
	full := filepath.Join(root, relPath)
	body, err := os.ReadFile(full)
	if err != nil {
		if os.IsNotExist(err) {
			return generated, nil
		}
		return "", err
	}
	existing := normalizeManagedText(string(body))
	start := strings.Index(existing, managedGuidanceStart)
	end := strings.Index(existing, managedGuidanceEnd)
	if start >= 0 && end > start {
		end += len(managedGuidanceEnd)
		updated := existing[:start] + generated + existing[end:]
		return strings.TrimRight(updated, "\n") + "\n", nil
	}
	if strings.TrimSpace(existing) == "" {
		return generated, nil
	}
	return strings.TrimRight(existing, "\n") + "\n\n" + generated, nil
}

func normalizeManagedText(body string) string {
	body = strings.ReplaceAll(body, "\r\n", "\n")
	body = strings.ReplaceAll(body, "\r", "\n")
	return body
}

func buildRootGeneratedGuideArtifact(root string, layout authoredLayout, graph PackageGraph, publication publishschema.State) (*Artifact, error) {
	paths, err := generatedArtifactInventory(root, layout, graph, publication, graph.Manifest.EnabledTargets())
	if err != nil {
		return nil, err
	}
	var body strings.Builder
	body.WriteString("# Generated Outputs\n\n")
	body.WriteString("This file is generated by `plugin-kit-ai generate`.\n")
	body.WriteString("Do not edit the paths below by hand. Edit only `")
	body.WriteString(layout.Path(""))
	body.WriteString("/`, then regenerate.\n\n")
	body.WriteString("This inventory covers the full plugin package across all enabled targets.\n\n")
	body.WriteString("## Boundary Docs\n\n")
	body.WriteString("These committed root docs are guidance files with a managed block, not plain generated outputs:\n\n")
	for _, rel := range boundaryDocsForLayout(layout) {
		body.WriteString("- `")
		body.WriteString(rel)
		body.WriteString("`\n")
	}
	body.WriteString("\n## Managed Generated Outputs\n\n")
	if managesReadme, err := shouldManageRootReadme(root); err != nil {
		return nil, err
	} else if managesReadme {
		body.WriteString("`README.md` is a generated root entrypoint that points readers to `")
		body.WriteString(layout.Path("README.md"))
		body.WriteString("`.\n\n")
	}
	for _, rel := range paths {
		body.WriteString("- `")
		body.WriteString(rel)
		body.WriteString("`\n")
	}
	body.WriteString("\n## Refresh\n\n")
	body.WriteString("```bash\n")
	body.WriteString("plugin-kit-ai normalize .\n")
	body.WriteString("plugin-kit-ai generate .\n")
	body.WriteString("plugin-kit-ai generate --check .\n")
	body.WriteString("```\n")
	return &Artifact{RelPath: "GENERATED.md", Content: []byte(body.String())}, nil
}

func generatedArtifactInventory(root string, layout authoredLayout, graph PackageGraph, publication publishschema.State, selected []string) ([]string, error) {
	artifactMap := map[string]struct{}{}
	boundarySet := map[string]struct{}{}
	for _, rel := range boundaryDocsForLayout(layout) {
		boundarySet[filepath.ToSlash(filepath.Clean(rel))] = struct{}{}
	}
	for _, target := range selected {
		generated, err := renderTargetArtifacts(root, graph, target)
		if err != nil {
			return nil, err
		}
		for _, artifact := range generated {
			rel := filepath.ToSlash(filepath.Clean(artifact.RelPath))
			if _, skip := boundarySet[rel]; skip {
				continue
			}
			artifactMap[rel] = struct{}{}
		}
	}
	publicationArtifacts, err := publicationexec.Generate(graph, publication, selected)
	if err != nil {
		return nil, err
	}
	for _, artifact := range publicationArtifacts {
		artifactMap[filepath.ToSlash(filepath.Clean(artifact.RelPath))] = struct{}{}
	}
	if readme, err := buildRootReadmeArtifact(root, layout, graph.Manifest); err != nil {
		return nil, err
	} else if readme != nil {
		artifactMap[readme.RelPath] = struct{}{}
	}
	artifactMap["GENERATED.md"] = struct{}{}
	return sortedKeys(artifactMap), nil
}

func boundaryDocsForLayout(layout authoredLayout) []string {
	if strings.TrimSpace(layout.Path("")) == "" {
		return nil
	}
	return []string{"CLAUDE.md", "AGENTS.md"}
}

func generatedGuideForLayout(layout authoredLayout) string {
	if strings.TrimSpace(layout.Path("")) == "" {
		return ""
	}
	return "GENERATED.md"
}
