package pluginmanifest

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/777genius/plugin-kit-ai/cli/internal/publicationexec"
	"github.com/777genius/plugin-kit-ai/cli/internal/publishschema"
	"github.com/777genius/plugin-kit-ai/cli/internal/scaffold"
)

func buildRootReadmeArtifact(root string, layout authoredLayout, manifest Manifest) (*Artifact, error) {
	if !layout.IsCanonical() {
		return nil, nil
	}
	authoredReadme := layout.Path("README.md")
	authoredReadmePath := filepath.Join(root, authoredReadme)
	if _, err := os.Stat(authoredReadmePath); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	title := strings.TrimSpace(manifest.Name)
	if title == "" {
		title = "plugin"
	}
	var body strings.Builder
	body.WriteString("# ")
	body.WriteString(title)
	body.WriteString("\n\n")
	body.WriteString("This file is generated by `plugin-kit-ai generate`.\n")
	body.WriteString("Do not edit it by hand. Edit files under `src/`, especially [`src/README.md`](./src/README.md).\n\n")
	body.WriteString("Start here:\n\n")
	body.WriteString("- full plugin guide: [`src/README.md`](./src/README.md)\n")
	body.WriteString("- boundary instructions for humans and agents: [`AGENTS.md`](./AGENTS.md)\n")
	body.WriteString("- generated root output inventory: [`GENERATED.md`](./GENERATED.md)\n\n")
	body.WriteString("This plugin root is the native/generated output surface for the supported targets.\n")
	artifact := Artifact{RelPath: "README.md", Content: []byte(body.String())}
	return &artifact, nil
}

func buildRootClaudeBoundaryArtifact(layout authoredLayout) (*Artifact, error) {
	if !layout.IsCanonical() {
		return nil, nil
	}
	body, _, err := scaffold.RenderTemplate("ROOT.CLAUDE.md.tmpl", scaffold.Data{})
	if err != nil {
		return nil, err
	}
	return &Artifact{RelPath: "CLAUDE.md", Content: body}, nil
}

func stripLeadingMarkdownTitle(body string) string {
	body = strings.ReplaceAll(body, "\r\n", "\n")
	lines := strings.Split(body, "\n")
	if len(lines) == 0 {
		return body
	}
	if strings.HasPrefix(strings.TrimSpace(lines[0]), "# ") {
		return strings.TrimLeft(strings.Join(lines[1:], "\n"), "\n")
	}
	return body
}

func buildRootGeneratedGuideArtifact(root string, layout authoredLayout, graph PackageGraph, publication publishschema.State) (*Artifact, error) {
	if !layout.IsCanonical() {
		return nil, nil
	}
	paths, err := generatedArtifactInventory(root, layout, graph, publication, graph.Manifest.EnabledTargets())
	if err != nil {
		return nil, err
	}
	var body strings.Builder
	body.WriteString("# Generated Outputs\n\n")
	body.WriteString("This file is generated by `plugin-kit-ai generate`.\n")
	body.WriteString("Do not edit the paths below by hand. Edit only `src/`, then regenerate.\n\n")
	body.WriteString("This inventory covers the full plugin package across all enabled targets.\n\n")
	body.WriteString("## Boundary Docs\n\n")
	body.WriteString("These committed root docs are guidance files and are not generated outputs:\n\n")
	for _, rel := range boundaryDocsForLayout(layout) {
		body.WriteString("- `")
		body.WriteString(rel)
		body.WriteString("`\n")
	}
	body.WriteString("\n## Managed Generated Outputs\n\n")
	body.WriteString("`README.md` is a generated root entrypoint that points readers to `src/README.md`.\n\n")
	for _, rel := range paths {
		body.WriteString("- `")
		body.WriteString(rel)
		body.WriteString("`\n")
	}
	body.WriteString("\n## Refresh\n\n")
	body.WriteString("```bash\n")
	body.WriteString("plugin-kit-ai normalize .\n")
	body.WriteString("plugin-kit-ai generate .\n")
	body.WriteString("plugin-kit-ai generate --check .\n")
	body.WriteString("```\n")
	return &Artifact{RelPath: "GENERATED.md", Content: []byte(body.String())}, nil
}

func generatedArtifactInventory(root string, layout authoredLayout, graph PackageGraph, publication publishschema.State, selected []string) ([]string, error) {
	artifactMap := map[string]struct{}{}
	boundarySet := map[string]struct{}{}
	for _, rel := range boundaryDocsForLayout(layout) {
		boundarySet[filepath.ToSlash(filepath.Clean(rel))] = struct{}{}
	}
	for _, target := range selected {
		generated, err := renderTargetArtifacts(root, graph, target)
		if err != nil {
			return nil, err
		}
		for _, artifact := range generated {
			rel := filepath.ToSlash(filepath.Clean(artifact.RelPath))
			if _, skip := boundarySet[rel]; skip {
				continue
			}
			artifactMap[rel] = struct{}{}
		}
	}
	publicationArtifacts, err := publicationexec.Generate(graph, publication, selected)
	if err != nil {
		return nil, err
	}
	for _, artifact := range publicationArtifacts {
		artifactMap[filepath.ToSlash(filepath.Clean(artifact.RelPath))] = struct{}{}
	}
	if readme, err := buildRootReadmeArtifact(root, layout, graph.Manifest); err != nil {
		return nil, err
	} else if readme != nil {
		artifactMap[readme.RelPath] = struct{}{}
	}
	artifactMap["GENERATED.md"] = struct{}{}
	return sortedKeys(artifactMap), nil
}

func boundaryDocsForLayout(layout authoredLayout) []string {
	if !layout.IsCanonical() {
		return nil
	}
	return []string{"CLAUDE.md", "AGENTS.md"}
}

func generatedGuideForLayout(layout authoredLayout) string {
	if !layout.IsCanonical() {
		return ""
	}
	return "GENERATED.md"
}
