package platformexec

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/777genius/plugin-kit-ai/cli/internal/codexmanifest"
	"github.com/777genius/plugin-kit-ai/cli/internal/pluginmodel"
)

func (codexPackageAdapter) Generate(root string, graph pluginmodel.PackageGraph, state pluginmodel.TargetState) ([]pluginmodel.Artifact, error) {
	extra, err := loadNativeExtraDoc(root, state, "manifest_extra", pluginmodel.NativeDocFormatJSON)
	if err != nil {
		return nil, err
	}
	meta := codexPackageMeta{
		Author:     manifestAuthorToCodex(graph.Manifest.Author),
		Homepage:   strings.TrimSpace(graph.Manifest.Homepage),
		Repository: strings.TrimSpace(graph.Manifest.Repository),
		License:    strings.TrimSpace(graph.Manifest.License),
		Keywords:   append([]string(nil), graph.Manifest.Keywords...),
	}
	override, _, err := readYAMLDoc[codexPackageMeta](root, state.DocPath("package_metadata"))
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", state.DocPath("package_metadata"), err)
	}
	mergeCodexPackageMeta(&meta, override)
	meta.Normalize()
	managedPaths := managedKeysForNativeDoc("codex-package", "manifest_extra")
	if err := pluginmodel.ValidateNativeExtraDocConflicts(extra, "codex-package manifest.extra.json", managedPaths); err != nil {
		return nil, err
	}
	doc := map[string]any{
		"name":        graph.Manifest.Name,
		"version":     graph.Manifest.Version,
		"description": graph.Manifest.Description,
	}
	meta.Apply(doc)
	if len(graph.Portable.Paths("skills")) > 0 {
		doc["skills"] = codexmanifest.SkillsRef
	}
	if graph.Portable.MCP != nil {
		doc["mcpServers"] = codexmanifest.MCPServersRef
	}

	var artifacts []pluginmodel.Artifact
	if rel := strings.TrimSpace(state.DocPath("interface")); rel != "" {
		body, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return nil, err
		}
		interfaceDoc, err := codexmanifest.ParseInterfaceDoc(body)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", rel, err)
		}
		doc["interface"] = interfaceDoc
	}
	if rel := strings.TrimSpace(state.DocPath("app_manifest")); rel != "" {
		body, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return nil, err
		}
		appDoc, err := codexmanifest.ParseAppManifestDoc(body)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", rel, err)
		}
		if codexmanifest.AppManifestEnabled(appDoc) {
			doc["apps"] = codexmanifest.AppsRef
			artifacts = append(artifacts, pluginmodel.Artifact{
				RelPath: ".app.json",
				Content: body,
			})
		}
	}
	if err := pluginmodel.MergeNativeExtraObject(doc, extra, "codex-package manifest.extra.json", managedPaths); err != nil {
		return nil, err
	}
	pluginJSON, err := marshalJSON(doc)
	if err != nil {
		return nil, err
	}
	artifacts = append(artifacts, pluginmodel.Artifact{
		RelPath: filepath.Join(".codex-plugin", "plugin.json"),
		Content: pluginJSON,
	})
	if graph.Portable.MCP != nil {
		projected, err := renderPortableMCPForTarget(graph.Portable.MCP, "codex-package")
		if err != nil {
			return nil, err
		}
		mcpJSON, err := marshalJSON(projected)
		if err != nil {
			return nil, err
		}
		artifacts = append(artifacts, pluginmodel.Artifact{
			RelPath: ".mcp.json",
			Content: mcpJSON,
		})
	}
	skillArtifacts, err := renderPortableSkills(root, graph.Portable.Paths("skills"), "skills")
	if err != nil {
		return nil, err
	}
	artifacts = append(artifacts, skillArtifacts...)
	return compactArtifacts(artifacts), nil
}

func (codexRuntimeAdapter) Generate(root string, graph pluginmodel.PackageGraph, state pluginmodel.TargetState) ([]pluginmodel.Artifact, error) {
	entrypoint := ""
	if graph.Launcher != nil {
		entrypoint = graph.Launcher.Entrypoint
	}
	if strings.TrimSpace(entrypoint) == "" {
		return nil, fmt.Errorf("required launcher missing: %s", pluginmodel.LauncherFileName)
	}
	model := ""
	if meta, ok, err := readYAMLDoc[codexRuntimeMeta](root, state.DocPath("package_metadata")); err != nil {
		return nil, fmt.Errorf("parse %s: %w", state.DocPath("package_metadata"), err)
	} else if ok {
		model = strings.TrimSpace(meta.ModelHint)
	}
	if strings.TrimSpace(model) == "" {
		model = "gpt-5.4-mini"
	}
	configExtra, err := loadNativeExtraDoc(root, state, "config_extra", pluginmodel.NativeDocFormatTOML)
	if err != nil {
		return nil, err
	}
	if err := pluginmodel.ValidateNativeExtraDocConflicts(configExtra, "codex-runtime config.extra.toml", managedKeysForNativeDoc("codex-runtime", "config_extra")); err != nil {
		return nil, err
	}
	var config bytes.Buffer
	config.WriteString("# Generated by plugin-kit-ai. DO NOT EDIT.\n")
	config.WriteString(fmt.Sprintf("model = %q\n", model))
	config.WriteString(fmt.Sprintf("notify = [%q, %q]\n", entrypoint, "notify"))
	if extraBody := pluginmodel.TrimmedExtraBody(configExtra); len(extraBody) > 0 {
		config.WriteByte('\n')
		config.Write(extraBody)
		config.WriteByte('\n')
	}
	artifacts := []pluginmodel.Artifact{{
		RelPath: filepath.Join(".codex", "config.toml"),
		Content: config.Bytes(),
	}}
	copied, err := copyArtifactDirs(root,
		artifactDir{src: authoredComponentDir(state, "commands", filepath.Join("targets", "codex-runtime", "commands")), dst: "commands"},
		artifactDir{src: authoredComponentDir(state, "contexts", filepath.Join("targets", "codex-runtime", "contexts")), dst: "contexts"},
	)
	if err != nil {
		return nil, err
	}
	return append(artifacts, copied...), nil
}
