package directoryv1

import (
	"encoding/base64"
	"errors"
	"fmt"
	"regexp"
)

var goIdentifierPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// ReleaseBootstrapEncoding is the deterministic release input copied from a
// published snapshot and detached envelope. Empty sequence/strings are the
// only valid pre-publication state; partial data can never signal readiness.
type ReleaseBootstrapEncoding struct {
	Sequence       uint64
	SnapshotBase64 string
	EnvelopeBase64 string
}

// EncodeReleaseBootstrap validates exact signed publication bytes and returns
// their deterministic source representation. Release automation can bind this
// result into the generated production constants without reserializing either
// signed artifact.
func EncodeReleaseBootstrap(snapshot, envelope []byte, trust TrustStore) (ReleaseBootstrapEncoding, error) {
	bundle, err := VerifyBundle(snapshot, envelope, trust)
	if err != nil {
		return ReleaseBootstrapEncoding{}, err
	}
	return ReleaseBootstrapEncoding{
		Sequence: bundle.Snapshot.Sequence, SnapshotBase64: base64.StdEncoding.EncodeToString(snapshot),
		EnvelopeBase64: base64.StdEncoding.EncodeToString(envelope),
	}, nil
}

// GenerateReleaseBootstrapSource produces the deterministic Go source that a
// release copies into the production bootstrap file. It accepts only a real,
// verified signed bundle; the pre-publication empty tuple is maintained by the
// checked-in placeholder rather than generated from invented bytes.
func GenerateReleaseBootstrapSource(packageName, variableName string, snapshot, envelope []byte, trust TrustStore) ([]byte, error) {
	if !goIdentifierPattern.MatchString(packageName) || !goIdentifierPattern.MatchString(variableName) {
		return nil, errors.New("invalid generated bootstrap Go identifier")
	}
	encoded, err := EncodeReleaseBootstrap(snapshot, envelope, trust)
	if err != nil {
		return nil, err
	}
	source := fmt.Sprintf(`// Code generated by the release-bound Directory bootstrap step; DO NOT EDIT.
package %s

import "github.com/777genius/plugin-kit-ai/install/integrationctl/agentplugins/adapters/directoryv1"

var %s = directoryv1.ReleaseBootstrapEncoding{
	Sequence:       %d,
	SnapshotBase64: %q,
	EnvelopeBase64: %q,
}
`, packageName, variableName, encoded.Sequence, encoded.SnapshotBase64, encoded.EnvelopeBase64)
	return []byte(source), nil
}

// DecodeReleaseBootstrap verifies generated constants and binds the declared
// release sequence to the signed artifacts. ready is false only for the exact
// empty pre-publication state.
func DecodeReleaseBootstrap(encoded ReleaseBootstrapEncoding, trust TrustStore) (embedded EmbeddedBundle, ready bool, err error) {
	if encoded.Sequence == 0 && encoded.SnapshotBase64 == "" && encoded.EnvelopeBase64 == "" {
		return EmbeddedBundle{}, false, nil
	}
	if encoded.Sequence == 0 || encoded.SnapshotBase64 == "" || encoded.EnvelopeBase64 == "" {
		return EmbeddedBundle{}, false, errors.New("partial generated directory bootstrap")
	}
	snapshot, err := base64.StdEncoding.Strict().DecodeString(encoded.SnapshotBase64)
	if err != nil {
		return EmbeddedBundle{}, false, fmt.Errorf("decode generated directory snapshot: %w", err)
	}
	envelope, err := base64.StdEncoding.Strict().DecodeString(encoded.EnvelopeBase64)
	if err != nil {
		return EmbeddedBundle{}, false, fmt.Errorf("decode generated directory envelope: %w", err)
	}
	bundle, err := VerifyBundle(snapshot, envelope, trust)
	if err != nil {
		return EmbeddedBundle{}, false, fmt.Errorf("verify generated directory bootstrap: %w", err)
	}
	if bundle.Snapshot.Sequence != encoded.Sequence {
		return EmbeddedBundle{}, false, fmt.Errorf("generated directory bootstrap sequence %d does not match signed sequence %d", encoded.Sequence, bundle.Snapshot.Sequence)
	}
	return EmbeddedBundle{Snapshot: snapshot, Envelope: envelope}, true, nil
}
